<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Operations;

use \tigris\core\Utils\SpeakeasyMetadata;
class SearchGetQueryParams
{
    /**
     * document id.
     * 
     * @var ?array<string> $ids
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=ids')]
    public ?array $ids = null;
    
	public function __construct()
	{
		$this->ids = null;
	}
}
