<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Operations;

use \tigris\core\Utils\SpeakeasyMetadata;
class SearchCreateByIdRequest
{
	
    public SearchCreateByIdPathParams $pathParams;
    
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \tigris\core\Models\Shared\CreateByIdRequest $request;
    
	public function __construct()
	{
		$this->pathParams = new \tigris\core\Models\Operations\SearchCreateByIdPathParams();
		$this->request = new \tigris\core\Models\Shared\CreateByIdRequest();
	}
}
