<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Operations;

use \tigris\core\Utils\SpeakeasyMetadata;
class SearchListIndexesQueryParams
{
    /**
     * Applicable only in case index is backed by Tigris collection. This is the database branch for the above collection. For primary database it can be omitted or "main" can be passed.
     * 
     * @var ?string $filterBranch
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=filter.branch')]
    public ?string $filterBranch = null;
    
    /**
     * Applicable only in case index is backed by Tigris collection.
     * 
     * @var ?string $filterCollection
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=filter.collection')]
    public ?string $filterCollection = null;
    
    /**
     * An index can be either managed by user explicitly then the type is set as "user" or the index is backed by Tigris collection. In case it is backed by Tigris collection the type is "tigris".
     * 
     * @var ?string $filterType
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=filter.type')]
    public ?string $filterType = null;
    
	public function __construct()
	{
		$this->filterBranch = null;
		$this->filterCollection = null;
		$this->filterType = null;
	}
}
