<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Operations;

use \tigris\core\Utils\SpeakeasyMetadata;
class SearchCreateByIdRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \tigris\core\Models\Shared\CreateByIdRequest $createByIdRequest;
    
    /**
     * document id.
     * 
     * @var string $id
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
    /**
     * index name where to create document.
     * 
     * @var string $index
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=index')]
    public string $index;
    
    /**
     * Tigris project name.
     * 
     * @var string $project
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=project')]
    public string $project;
    
	public function __construct()
	{
		$this->createByIdRequest = new \tigris\core\Models\Shared\CreateByIdRequest();
		$this->id = "";
		$this->index = "";
		$this->project = "";
	}
}
