<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Operations;

use \tigris\core\Utils\SpeakeasyMetadata;
class TigrisDeleteProjectRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \tigris\core\Models\Shared\DeleteProjectRequest $deleteProjectRequest;
    
    /**
     * Delete Project with this name. <p></p>**Note**: Deletes all resources under this project. Use with caution.
     * 
     * @var string $project
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=project')]
    public string $project;
    
	public function __construct()
	{
		$this->deleteProjectRequest = new \tigris\core\Models\Shared\DeleteProjectRequest();
		$this->project = "";
	}
}
