<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Operations;

use \tigris\core\Utils\SpeakeasyMetadata;
class TigrisListCollectionsQueryParams
{
    /**
     * Optionally specify a database branch name to perform operation on
     * 
     * @var ?string $branch
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=branch')]
    public ?string $branch = null;
    
	public function __construct()
	{
		$this->branch = null;
	}
}
