<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Operations;

use \tigris\core\Utils\SpeakeasyMetadata;
class TigrisCreateBranchRequest
{
    /**
     * $requestBody
     * 
     * @var array<string, mixed> $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public array $requestBody;
    
    /**
     * Name of the database branch to be created. <p></p>**Note**: `main` is a reserved branch name for primary database and is automatically created with CreateProject
     * 
     * @var string $branch
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=branch')]
    public string $branch;
    
    /**
     * Create a database branch in this project
     * 
     * @var string $project
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=project')]
    public string $project;
    
	public function __construct()
	{
		$this->requestBody = [];
		$this->branch = "";
		$this->project = "";
	}
}
