<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Operations;

use \tigris\core\Utils\SpeakeasyMetadata;
class TigrisCommitTransactionRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \tigris\core\Models\Shared\CommitTransactionRequest $commitTransactionRequest;
    
    /**
     * Project name whose DB this transaction belongs to.
     * 
     * @var string $project
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=project')]
    public string $project;
    
	public function __construct()
	{
		$this->commitTransactionRequest = new \tigris\core\Models\Shared\CommitTransactionRequest();
		$this->project = "";
	}
}
