<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Operations;

use \tigris\core\Utils\SpeakeasyMetadata;
class TigrisCreateProjectRequest
{
    /**
     * $requestBody
     * 
     * @var array<string, mixed> $requestBody
     */
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public array $requestBody;
    
    /**
     * Create project with this name.
     * 
     * @var string $project
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=project')]
    public string $project;
    
	public function __construct()
	{
		$this->requestBody = [];
		$this->project = "";
	}
}
