<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class BranchInfo
{
    /**
     * Branch name
     * 
     * @var ?string $branch
     */
	#[\JMS\Serializer\Annotation\SerializedName('branch')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $branch = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\BranchMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?BranchMetadata $metadata = null;
    
	public function __construct()
	{
		$this->branch = null;
		$this->metadata = null;
	}
}
