<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class CollectionDescription
{
    /**
     * Name of the collection.
     * 
     * @var ?string $collection
     */
	#[\JMS\Serializer\Annotation\SerializedName('collection')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $collection = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\CollectionMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CollectionMetadata $metadata = null;
    
    /**
     * Collections schema
     * 
     * @var ?\tigris\core\Models\Shared\CollectionDescriptionSchema $schema
     */
	#[\JMS\Serializer\Annotation\SerializedName('schema')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\CollectionDescriptionSchema')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CollectionDescriptionSchema $schema = null;
    
    /**
     * Collection size in bytes
     * 
     * @var ?int $size
     */
	#[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $size = null;
    
	public function __construct()
	{
		$this->collection = null;
		$this->metadata = null;
		$this->schema = null;
		$this->size = null;
	}
}
