<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class CreateOrUpdateCollectionRequest
{
    /**
     * Optionally specify a database branch name to perform operation on
     * 
     * @var ?string $branch
     */
	#[\JMS\Serializer\Annotation\SerializedName('branch')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $branch = null;
    
    /**
     * If set to `true` then the update schema request to the collection will fail by returning a conflict with HTTP Status code 409. The default is false.
     * 
     * @var ?bool $onlyCreate
     */
	#[\JMS\Serializer\Annotation\SerializedName('only_create')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $onlyCreate = null;
    
    /**
     * Collection requests modifying options.
     * 
     * @var ?\tigris\core\Models\Shared\CollectionOptions $options
     */
	#[\JMS\Serializer\Annotation\SerializedName('options')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\CollectionOptions')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CollectionOptions $options = null;
    
    /**
     * The schema specifications are same as JSON schema specification defined <a href="https://json-schema.org/specification.html" title="here">here</a>.<p></p> Schema example: `{  "title": "user",  "description": "Collection of documents with details of users",  "properties": {    "id": {      "description": "A unique identifier for the user",      "type": "integer"    },    "name": {      "description": "Name of the user",      "type": "string",      "maxLength": 128    },    "balance": {      "description": "User account balance",      "type": "number"    }  },  "primary_key": ["id"] }`
     * 
     * @var ?\tigris\core\Models\Shared\CreateOrUpdateCollectionRequestSchema $schema
     */
	#[\JMS\Serializer\Annotation\SerializedName('schema')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\CreateOrUpdateCollectionRequestSchema')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CreateOrUpdateCollectionRequestSchema $schema = null;
    
	public function __construct()
	{
		$this->branch = null;
		$this->onlyCreate = null;
		$this->options = null;
		$this->schema = null;
	}
}
