<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * DeleteAppKeyResponse - AppKeys returns the flag to convey if app key was deleted
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class DeleteAppKeyResponse
{
    /**
     * status flag for delete operation
     * 
     * @var ?bool $deleted
     */
	#[\JMS\Serializer\Annotation\SerializedName('deleted')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $deleted = null;
    
	public function __construct()
	{
		$this->deleted = null;
	}
}
