<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * DeleteByQueryResponse - OK
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class DeleteByQueryResponse
{
    /**
     * The number of documents deleted.
     * 
     * @var ?int $count
     */
	#[\JMS\Serializer\Annotation\SerializedName('count')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $count = null;
    
	public function __construct()
	{
		$this->count = null;
	}
}
