<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * DescribeDatabaseResponse - A detailed description of the database and all the associated collections. Description of the collection includes schema details as well.
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class DescribeDatabaseResponse
{
    /**
     * List of all the branches in this database
     * 
     * @var ?array<string> $branches
     */
	#[\JMS\Serializer\Annotation\SerializedName('branches')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $branches = null;
    
    /**
     * A detailed description about all the collections. The description returns collection metadata and the schema.
     * 
     * @var ?array<\tigris\core\Models\Shared\CollectionDescription> $collections
     */
	#[\JMS\Serializer\Annotation\SerializedName('collections')]
    #[\JMS\Serializer\Annotation\Type('array<tigris\core\Models\Shared\CollectionDescription>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $collections = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\DatabaseMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?DatabaseMetadata $metadata = null;
    
    /**
     * Sum of all the collections sizes present in this database
     * 
     * @var ?int $size
     */
	#[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $size = null;
    
	public function __construct()
	{
		$this->branches = null;
		$this->collections = null;
		$this->metadata = null;
		$this->size = null;
	}
}
