<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * DescribeCollectionResponse - A detailed description of the collection. The description returns collection metadata and the schema.
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class DescribeCollectionResponse
{
    /**
     * Name of the collection.
     * 
     * @var ?string $collection
     */
	#[\JMS\Serializer\Annotation\SerializedName('collection')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $collection = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\CollectionMetadata')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?CollectionMetadata $metadata = null;
    
    /**
     * Schema of this collection.
     * 
     * @var ?\tigris\core\Models\Shared\DescribeCollectionResponseSchema $schema
     */
	#[\JMS\Serializer\Annotation\SerializedName('schema')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\DescribeCollectionResponseSchema')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?DescribeCollectionResponseSchema $schema = null;
    
    /**
     * The size of this collection in bytes.
     * 
     * @var ?int $size
     */
	#[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $size = null;
    
	public function __construct()
	{
		$this->collection = null;
		$this->metadata = null;
		$this->schema = null;
		$this->size = null;
	}
}
