<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/** The status code is a short, machine parsable string, which uniquely identifies the error type. Tigris to HTTP code mapping [here](/reference/http-code) */
enum ErrorCode: string
{
    case Ok = 'OK';
    case Cancelled = 'CANCELLED';
    case Unknown = 'UNKNOWN';
    case InvalidArgument = 'INVALID_ARGUMENT';
    case DeadlineExceeded = 'DEADLINE_EXCEEDED';
    case NotFound = 'NOT_FOUND';
    case AlreadyExists = 'ALREADY_EXISTS';
    case PermissionDenied = 'PERMISSION_DENIED';
    case ResourceExhausted = 'RESOURCE_EXHAUSTED';
    case FailedPrecondition = 'FAILED_PRECONDITION';
    case Aborted = 'ABORTED';
    case OutOfRange = 'OUT_OF_RANGE';
    case Unimplemented = 'UNIMPLEMENTED';
    case Internal = 'INTERNAL';
    case Unavailable = 'UNAVAILABLE';
    case DataLoss = 'DATA_LOSS';
    case Unauthenticated = 'UNAUTHENTICATED';
    case Conflict = 'CONFLICT';
    case BadGateway = 'BAD_GATEWAY';
    case MethodNotAllowed = 'METHOD_NOT_ALLOWED';
}
