<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * Fields - To read specific fields from a document. Default is all.
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class Fields
{
	public function __construct()
	{
	}
}
