<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class GetDocumentResponse
{
    /**
     * An array of documents.
     * 
     * @var ?array<\tigris\core\Models\Shared\IndexDoc> $documents
     */
	#[\JMS\Serializer\Annotation\SerializedName('documents')]
    #[\JMS\Serializer\Annotation\Type('array<tigris\core\Models\Shared\IndexDoc>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $documents = null;
    
	public function __construct()
	{
		$this->documents = null;
	}
}
