<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * HealthCheckResponse - OK
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class HealthCheckResponse
{
	#[\JMS\Serializer\Annotation\SerializedName('response')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $response = null;
    
	public function __construct()
	{
		$this->response = null;
	}
}
