<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class IndexDoc
{
    /**
     * Actual search document
     * 
     * @var ?string $doc
     */
	#[\JMS\Serializer\Annotation\SerializedName('doc')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $doc = null;
    
    /**
     * Contains metadata related to the search hit, has information about document created_at/updated_at as well.
     * 
     * @var ?\tigris\core\Models\Shared\DocMeta $metadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\DocMeta')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?DocMeta $metadata = null;
    
	public function __construct()
	{
		$this->doc = null;
		$this->metadata = null;
	}
}
