<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * InsertRequestOptions - additional options for insert requests.
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class InsertRequestOptions
{
    /**
     * Additional options to modify write requests.
     * 
     * @var ?array<string, mixed> $writeOptions
     */
	#[\JMS\Serializer\Annotation\SerializedName('write_options')]
    #[\JMS\Serializer\Annotation\Type('array<string, mixed>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $writeOptions = null;
    
	public function __construct()
	{
		$this->writeOptions = null;
	}
}
