<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class InsertRequest
{
    /**
     * Optionally specify a database branch name to perform operation on
     * 
     * @var ?string $branch
     */
	#[\JMS\Serializer\Annotation\SerializedName('branch')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $branch = null;
    
    /**
     * Array of documents to insert. Each document is a JSON object.
     * 
     * @var ?array<\tigris\core\Models\Shared\InsertRequestDocuments> $documents
     */
	#[\JMS\Serializer\Annotation\SerializedName('documents')]
    #[\JMS\Serializer\Annotation\Type('array<tigris\core\Models\Shared\InsertRequestDocuments>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $documents = null;
    
    /**
     * additional options for insert requests.
     * 
     * @var ?\tigris\core\Models\Shared\InsertRequestOptions $options
     */
	#[\JMS\Serializer\Annotation\SerializedName('options')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\InsertRequestOptions')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?InsertRequestOptions $options = null;
    
	public function __construct()
	{
		$this->branch = null;
		$this->documents = null;
		$this->options = null;
	}
}
