<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class ListSubscriptionResponse
{
    /**
     * $devices
     * 
     * @var ?array<string> $devices
     */
	#[\JMS\Serializer\Annotation\SerializedName('devices')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $devices = null;
    
	public function __construct()
	{
		$this->devices = null;
	}
}
