<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class ListBranchesResponse
{
    /**
     * List of all the branches in this database
     * 
     * @var ?array<\tigris\core\Models\Shared\BranchInfo> $branches
     */
	#[\JMS\Serializer\Annotation\SerializedName('branches')]
    #[\JMS\Serializer\Annotation\Type('array<tigris\core\Models\Shared\BranchInfo>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $branches = null;
    
	public function __construct()
	{
		$this->branches = null;
	}
}
