<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * ListIndexesResponse - OK
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class ListIndexesResponse
{
    /**
     * List of indexes.
     * 
     * @var ?array<\tigris\core\Models\Shared\IndexInfo> $indexes
     */
	#[\JMS\Serializer\Annotation\SerializedName('indexes')]
    #[\JMS\Serializer\Annotation\Type('array<tigris\core\Models\Shared\IndexInfo>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $indexes = null;
    
	public function __construct()
	{
		$this->indexes = null;
	}
}
