<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * ListCollectionsResponse - OK
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class ListCollectionsResponse
{
    /**
     * List of the collections info in the database.
     * 
     * @var ?array<\tigris\core\Models\Shared\CollectionInfo> $collections
     */
	#[\JMS\Serializer\Annotation\SerializedName('collections')]
    #[\JMS\Serializer\Annotation\Type('array<tigris\core\Models\Shared\CollectionInfo>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $collections = null;
    
	public function __construct()
	{
		$this->collections = null;
	}
}
