<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * ListProjectsResponse - OK
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class ListProjectsResponse
{
    /**
     * List of the projects.
     * 
     * @var ?array<\tigris\core\Models\Shared\ProjectInfo> $projects
     */
	#[\JMS\Serializer\Annotation\SerializedName('projects')]
    #[\JMS\Serializer\Annotation\Type('array<tigris\core\Models\Shared\ProjectInfo>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $projects = null;
    
	public function __construct()
	{
		$this->projects = null;
	}
}
