<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * ListNamespacesResponse - OK
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class ListNamespacesResponse
{
    /**
     * $namespaces
     * 
     * @var ?array<\tigris\core\Models\Shared\NamespaceInfo> $namespaces
     */
	#[\JMS\Serializer\Annotation\SerializedName('namespaces')]
    #[\JMS\Serializer\Annotation\Type('array<tigris\core\Models\Shared\NamespaceInfo>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $namespaces = null;
    
	public function __construct()
	{
		$this->namespaces = null;
	}
}
