<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


enum QueryTimeSeriesMetricsRequestFunction: string
{
    case Rate = 'RATE';
    case Count = 'COUNT';
    case None = 'NONE';
}
