<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * QuotaLimitsResponse - Contains current quota limits
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class QuotaLimitsResponse
{
    /**
     * Number of allowed read units per second
     * 
     * @var ?int $readUnits
     */
	#[\JMS\Serializer\Annotation\SerializedName('ReadUnits')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $readUnits = null;
    
    /**
     * Maximum number of bytes allowed to store
     * 
     * @var ?int $storageSize
     */
	#[\JMS\Serializer\Annotation\SerializedName('StorageSize')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $storageSize = null;
    
    /**
     * Number of allowed write units per second
     * 
     * @var ?int $writeUnits
     */
	#[\JMS\Serializer\Annotation\SerializedName('WriteUnits')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $writeUnits = null;
    
	public function __construct()
	{
		$this->readUnits = null;
		$this->storageSize = null;
		$this->writeUnits = null;
	}
}
