<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * QuotaUsageResponse - Contains current quota usage
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class QuotaUsageResponse
{
    /**
     * Number of read units used per second
     * 
     * @var ?int $readUnits
     */
	#[\JMS\Serializer\Annotation\SerializedName('ReadUnits')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $readUnits = null;
    
    /**
     * Number of read units throttled per second. Units which was rejected with "resource exhausted error".
     * 
     * @var ?int $readUnitsThrottled
     */
	#[\JMS\Serializer\Annotation\SerializedName('ReadUnitsThrottled')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $readUnitsThrottled = null;
    
    /**
     * Number of bytes stored
     * 
     * @var ?int $storageSize
     */
	#[\JMS\Serializer\Annotation\SerializedName('StorageSize')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $storageSize = null;
    
    /**
     * Number of bytes throttled. Number of bytes which were attempted to write in excess of quota and were rejected.
     * 
     * @var ?int $storageSizeThrottled
     */
	#[\JMS\Serializer\Annotation\SerializedName('StorageSizeThrottled')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $storageSizeThrottled = null;
    
    /**
     * Number of write units used per second
     * 
     * @var ?int $writeUnits
     */
	#[\JMS\Serializer\Annotation\SerializedName('WriteUnits')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $writeUnits = null;
    
    /**
     * Number of write units throttled per second. Units which was rejected with "resource exhausted error".
     * 
     * @var ?int $writeUnitsThrottled
     */
	#[\JMS\Serializer\Annotation\SerializedName('WriteUnitsThrottled')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $writeUnitsThrottled = null;
    
	public function __construct()
	{
		$this->readUnits = null;
		$this->readUnitsThrottled = null;
		$this->storageSize = null;
		$this->storageSizeThrottled = null;
		$this->writeUnits = null;
		$this->writeUnitsThrottled = null;
	}
}
