<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * QuotaUsageRequest - Request current namespace quota usage
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class QuotaUsageRequest
{
	public function __construct()
	{
	}
}
