<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * ReadResponseData - Object containing the collection document.
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class ReadResponseData
{
	public function __construct()
	{
	}
}
