<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * ReplaceRequestOptions - Additional options for replace requests.
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class ReplaceRequestOptions
{
    /**
     * Additional options to modify write requests.
     * 
     * @var ?\tigris\core\Models\Shared\WriteOptions $writeOptions
     */
	#[\JMS\Serializer\Annotation\SerializedName('write_options')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\WriteOptions')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?WriteOptions $writeOptions = null;
    
	public function __construct()
	{
		$this->writeOptions = null;
	}
}
