<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


enum RollupFunctionAggregator: string
{
    case RollupAggregatorSum = 'ROLLUP_AGGREGATOR_SUM';
    case RollupAggregatorCount = 'ROLLUP_AGGREGATOR_COUNT';
    case RollupAggregatorMin = 'ROLLUP_AGGREGATOR_MIN';
    case RollupAggregatorMax = 'ROLLUP_AGGREGATOR_MAX';
    case RollupAggregatorAvg = 'ROLLUP_AGGREGATOR_AVG';
}
