<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * SearchRequestFacet - Facet query to aggregate results on given fields. The field name for the facet search can be passed like this `{"brand": { "size": 10 }}` where the size controls the total facets for this field.
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class SearchRequestFacet
{
	public function __construct()
	{
	}
}
