<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class SearchHit
{
    /**
     * Actual search document
     * 
     * @var ?\tigris\core\Models\Shared\SearchHitData $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\SearchHitData')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SearchHitData $data = null;
    
    /**
     * Contains metadata related to the search hit, has information about document created_at/updated_at as well.
     * 
     * @var ?\tigris\core\Models\Shared\SearchHitMeta $metadata
     */
	#[\JMS\Serializer\Annotation\SerializedName('metadata')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\SearchHitMeta')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?SearchHitMeta $metadata = null;
    
	public function __construct()
	{
		$this->data = null;
		$this->metadata = null;
	}
}
