<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * SearchRequestFilter - Filter stacks on top of query results to further narrow down the results. Similar to `ReadRequest.filter`
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class SearchRequestFilter
{
	public function __construct()
	{
	}
}
