<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class SearchMetadata
{
    /**
     * Total number of search results across all pages
     * 
     * @var ?int $found
     */
	#[\JMS\Serializer\Annotation\SerializedName('found')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $found = null;
    
    /**
     * Pagination metadata for SearchResponse
     * 
     * @var ?\tigris\core\Models\Shared\Page $page
     */
	#[\JMS\Serializer\Annotation\SerializedName('page')]
    #[\JMS\Serializer\Annotation\Type('tigris\core\Models\Shared\Page')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Page $page = null;
    
    /**
     * Number representing the total pages of results
     * 
     * @var ?int $totalPages
     */
	#[\JMS\Serializer\Annotation\SerializedName('total_pages')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $totalPages = null;
    
	public function __construct()
	{
		$this->found = null;
		$this->page = null;
		$this->totalPages = null;
	}
}
