<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class SetRequest
{
    /**
     * optional - ttl specific to this key in second
     * 
     * @var ?int $ex
     */
	#[\JMS\Serializer\Annotation\SerializedName('ex')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ex = null;
    
    /**
     * set only if the key doesn't exist
     * 
     * @var ?bool $nx
     */
	#[\JMS\Serializer\Annotation\SerializedName('nx')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $nx = null;
    
    /**
     * optional - ttl specific to this key in millisecond
     * 
     * @var ?int $px
     */
	#[\JMS\Serializer\Annotation\SerializedName('px')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $px = null;
    
    /**
     * free form byte[] value
     * 
     * @var ?string $value
     */
	#[\JMS\Serializer\Annotation\SerializedName('value')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $value = null;
    
    /**
     * set only if the key exist
     * 
     * @var ?bool $xx
     */
	#[\JMS\Serializer\Annotation\SerializedName('xx')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $xx = null;
    
	public function __construct()
	{
		$this->ex = null;
		$this->nx = null;
		$this->px = null;
		$this->value = null;
		$this->xx = null;
	}
}
