<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * Sort - Array of fields and corresponding sort orders to order the results `[{ "salary": "$desc" }]`
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class Sort
{
	public function __construct()
	{
	}
}
