<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


enum SpaceAggregation: string
{
    case Avg = 'AVG';
    case Min = 'MIN';
    case Max = 'MAX';
    case Sum = 'SUM';
}
