<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * TransactionOptions - Options that can be used to modify the transaction semantics.
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class TransactionOptions
{
	public function __construct()
	{
	}
}
