<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


class UpdateUserMetadataRequestValue
{
	public function __construct()
	{
	}
}
