<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace tigris\core\Models\Shared;


/**
 * UpdateRequestFields - Fields contains set of fields with the values which need to be updated. Should be proper JSON object.
 * 
 * @package tigris\core\Models\Shared
 * @access public
 */
class UpdateRequestFields
{
	public function __construct()
	{
	}
}
